/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-04-17 07:33:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex01.*;
import java.util.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>댓글관리</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("\t\t#page{width:800px; background:#aeb2fe; margin:auto; padding:10px;}\r\n");
      out.write("\t\th1{text-align:center;}\r\n");
      out.write("\t\t.box{width:755px; border:1px solid white; padding:10px;\r\n");
      out.write("\t\t\tmargin:auto; margin:10px;}\r\n");
      out.write("\t\t.date{width:150px; font-size:10px; color:white; float:left;}\r\n");
      out.write("\t\t#content{margin:10px}\r\n");
      out.write("\t\t.btnLike{color:red;}\r\n");
      out.write("\t\t.cnt{font-size:13px;}\r\n");
      out.write("\t\t.like{float:right;}\r\n");
      out.write("\t</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"page\">\r\n");
      out.write("\t\t<h1>[댓글관리]</h1>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"text\" id=\"content\" size=50>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"저장\" id=\"btnInsert\">\r\n");
      out.write("\t\t\t");

				ReplyDAO dao=new ReplyDAO();
				ArrayList<ReplyVO> list=dao.list();
				for(int i=0; i<list.size(); i++){
					ReplyVO vo=list.get(i);
					int rno=vo.getRno();
					String content=vo.getContent();
					Date wdate=vo.getWdate();
					int cnt=vo.getCnt();
					out.println("<div class=box>");
					out.println("<div class=title>");
					out.println("<span class=date>" + wdate + "</span>");
					out.println("<div class=like rno=" + rno + ">");
					out.println("<button class=btnLike>♥</button>");
					out.println("<span class=cnt>" + cnt + "</span>");
					out.println("<button class=delete>삭제</button>");
					out.println("</div>");
					out.println("</div>");
					out.println("<div class=content>" + content + "</div>");
					out.println("</div>");
				}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\".box\").on(\"click\", \".delete\", function(){\r\n");
      out.write("\t\tvar rno=$(this).parent().attr(\"rno\");\r\n");
      out.write("\t\tif(confirm(rno + \"번을 삭제하시겠습니까?\")==false) return;\r\n");
      out.write("\t\tlocation.href=\"sqlDelete.jsp?rno=\" + rno;\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".box\").on(\"click\", \".btnLike\", function(){\r\n");
      out.write("\t\tvar rno=$(this).parent().attr(\"rno\");\r\n");
      out.write("\t\tif(confirm(rno + \"번을 좋아요 누르시겠습니까?\")==false) return;\r\n");
      out.write("\t\tlocation.href=\"sqlUpdate.jsp?rno=\" + rno;\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#btnInsert\").on(\"click\", function(){\r\n");
      out.write("\t\tif(confirm(\"댓글을 저장하시겠습니까?\")==false) return;\r\n");
      out.write("\t\tvar content=$(\"#content\").val();\r\n");
      out.write("\t\tif(content==\"\"){\r\n");
      out.write("\t\t\talert(\"내용을 입력하세요!\")\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tlocation.href=\"sqlInsert.jsp?content=\" + content;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
