/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-05-06 05:53:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.courses;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ex0429.*;
import java.util.*;
import org.json.simple.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta charset=\"UTF-8\">\r\n");
      out.write("   <title>강좌목록</title>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"../home.css\">\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-1.9.1.js\"></script>\r\n");
      out.write("   <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div id=\"menu\">\r\n");
      out.write("      <a href=\"/ex0429/professors/list.jsp\">교수관리</a>\r\n");
      out.write("      <a href=\"/ex0429/students/list.jsp\">학생관리</a>\r\n");
      out.write("      <a href=\"/ex0429/courses/list.jsp\">강좌관리</a> \t\r\n");
      out.write("   </div>\r\n");
      out.write("   <h1>[ COURSES LIST ]</h1>\r\n");
      out.write("   <table id=\"tbl\" width=700 border=1>\r\n");
      out.write("      <tr class=\"title\">\r\n");
      out.write("         <td>강좌번호</td>\r\n");
      out.write("         <td>강좌명</td>\r\n");
      out.write("         <td>강의실</td>\r\n");
      out.write("         <td>담당교수</td>\r\n");
      out.write("         <td>성적입력</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");

         CDAO cdao=new CDAO();
         ArrayList<CVO> list=cdao.list("%%");
         for(CVO vo:list){
            out.println("<tr class=row>");
            out.println("<td class=lcode>" + vo.getLcode() + "</td>");
            out.println("<td class=lname>" + vo.getLname() + "</td>");
            out.println("<td>" + vo.getRoom() + "</td>");
            out.println("<td>" + vo.getInstructor() + "</td>");
            out.println("<td><button>성적입력</button></td>");
            out.println("</tr>");
         }
      
      out.write("\r\n");
      out.write("   </table>\r\n");
      out.write("   <div id=\"enroll\">\r\n");
      out.write("      <div id=\"courses\">\r\n");
      out.write("         강좌번호: <span id=\"lcode\" style=\"margin-right:50px;\"></span>\r\n");
      out.write("         강좌명: <span id=\"lname\"></span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <input type=\"button\" value=\"선택수정\" id=btnSave>\r\n");
      out.write("\t  <table id=\"etbl\" width=700 border=1></table>\r\n");
      out.write("\t  <script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t  <tr class=title>\r\n");
      out.write("\t\t\t <td><input type=checkbox id=chkAll></td>\r\n");
      out.write("\t \t\t <td>학번</td>\r\n");
      out.write("     \t\t <td>학생명</td>\r\n");
      out.write("\t\t\t  <td>점수</td>\r\n");
      out.write("\t\t\t  <td>수강신청일</td>\r\n");
      out.write("\t\t\t  <td>수정</td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  {{#each elist}}\r\n");
      out.write("\t\t\t  <tr class=row>\r\n");
      out.write("\t\t\t\t  <td><input type=checkbox class=chk></td>\r\n");
      out.write("\t\t\t\t  <td class=scode>{{scode}}</td>\r\n");
      out.write("\t\t\t\t  <td class=sname>{{sname}}</td>\r\n");
      out.write("\t\t\t\t  <td><input size=2 type=text class=grade value={{grade}}></td>\r\n");
      out.write("\t\t\t\t  <td class=date>{{edate}}</td>\r\n");
      out.write("\t\t\t\t  <td><button>수정</button></td>\r\n");
      out.write("\t\t\t  </tr>\r\n");
      out.write("\t \t {{/each}}\r\n");
      out.write("\t  </script>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar lcode;\r\n");
      out.write("\tgetList();\r\n");
      out.write("\r\n");
      out.write("   $(\"#tbl\").on(\"click\", \".row button\", function(){\r\n");
      out.write("      var row=$(this).parent().parent();\r\n");
      out.write("      lcode=row.find(\".lcode\").html();\r\n");
      out.write("      var lname=row.find(\".lname\").html();\r\n");
      out.write("      $(\"#lcode\").html(lcode);\r\n");
      out.write("      $(\"#lname\").html(lname);\r\n");
      out.write("      $(\"#enroll\").show();\r\n");
      out.write("      getList();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("\tfunction getList(){\r\n");
      out.write("\t\tlcode=$(\"#lcode\").html();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"get\",\r\n");
      out.write("\t\t\turl:\"json.jsp\",\r\n");
      out.write("\t\t\tdata:{\"lcode\":lcode},\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#etbl\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 전체선택 버튼을 클릭했을 때\r\n");
      out.write("\t$(\"#etbl\").on(\"click\", \"#chkAll\", function(){\r\n");
      out.write("\t\tif($(this).is(\":checked\")){\r\n");
      out.write("\t\t\t$(\"#etbl .row .chk\").each(function(){\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\", true);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#etbl .row .chk\").each(function(){\r\n");
      out.write("\t\t\t\t$(this).prop(\"checked\", false);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 선택수정 버튼을 클릭했을 때\r\n");
      out.write("\t$(\"#btnSave\").on(\"click\", function(){\r\n");
      out.write("\t\tif(confirm(\"선택수정하시겠습니까?\")==false) return;\r\n");
      out.write("\t\t$(\"#etbl .row .chk:checked\").each(function(){\r\n");
      out.write("\t\t\tvar row=$(this).parent().parent();\r\n");
      out.write("\t\t\tvar scode=row.find(\".scode\").html();\r\n");
      out.write("\t\t\tvar grade=row.find(\".grade\").val();\r\n");
      out.write("\t\t\t$(this).prop(\"checked\", false);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\turl:\"update.jsp\",\r\n");
      out.write("\t\t\t\tdata:{\"scode\":scode, \"lcode\":lcode, \"grade\":grade},\r\n");
      out.write("\t\t\t\tsuccess:function(){}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#etbl #chkAll\").prop(\"checked\", false);\r\n");
      out.write("\t\talert(\"수정되었습니다.\");\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t// 수정버튼을 클릭했을때\r\n");
      out.write("\t$(\"#etbl\").on(\"click\", \".row button\", function(){\r\n");
      out.write("\t   if(confirm(\"수정하시겠습니까?\")==false) return;\r\n");
      out.write("\t   lcode=$(\"#lcode\").html();\r\n");
      out.write("\t   var row=$(this).parent().parent();\r\n");
      out.write("\t   var scode=row.find(\".scode\").html();\r\n");
      out.write("\t   var grade=row.find(\".grade\").val();\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t      type:\"post\",\r\n");
      out.write("\t      url:\"update.jsp\",\r\n");
      out.write("\t      data:{\"scode\":scode, \"lcode\":lcode, \"grade\":grade},\r\n");
      out.write("\t      success:function(){\r\n");
      out.write("\t         alert(\"수정되었습니다.\");\r\n");
      out.write("\t         getList();\r\n");
      out.write("\t      },\r\n");
      out.write("\t      error:function(){\r\n");
      out.write("\t         alert(\"수정실패했습니다.\");\r\n");
      out.write("\t      }\r\n");
      out.write("\t   });\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
